config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('news/', include('news.urls', namespace='news')),
    path('announcements/', include('announcements.urls', namespace='announcements')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.apps import MainConfig
from main.views import (CompanyListView, CompanyDetailView,
                        CompanyCreateView, CompanyUpdateView, IndexView,
                        OfficeListView, OfficeDetailView, OfficeCreateView,
                        OfficeUpdateView, contacts, CompanyDeleteView,
                        OfficeDeleteView, BookingCreateView, CarsListView, CarsDetailView,
                        CarsCreateView, CarsUpdateView, CarsDeleteView, User_requestCreateView, User_requestListView,
                        User_requestDetailView, User_requestDeleteView, User_requestUpdateView, info, send_feedback,
                        User_requestStatusUpdateView, BookingListView, BookingUpdateView, BookingStatusUpdateView)

app_name = MainConfig.name

urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('contacts/', contacts, name='contacts'),
    path('company_list', CompanyListView.as_view(), name='labtest_list'),
    path('company/<int:pk>', CompanyDetailView.as_view(), name='labtest_detail'),
    path('company_create/', CompanyCreateView.as_view(), name='labtest_create'),
    path('company_update/<int:pk>', CompanyUpdateView.as_view(), name='labtest_update'),
    path('company_delete/<int:pk>', CompanyDeleteView.as_view(), name='labtest_delete'),

    path('office_list', OfficeListView.as_view(), name='office_list'),
    path('office/<int:pk>', OfficeDetailView.as_view(), name='office_detail'),
    path('office_create/', OfficeCreateView.as_view(), name='office_create'),
    path('office_update/<int:pk>', OfficeUpdateView.as_view(), name='office_update'),
    path('office_delete/<int:pk>', OfficeDeleteView.as_view(), name='office_delete'),

    path('booking_create/', BookingCreateView.as_view(), name='booking_create'),
    path('booking_list', BookingListView.as_view(), name='booking_list'),
    path('booking_update/<int:pk>', BookingUpdateView.as_view(), name='booking_update'),
    path('booking/update/<int:pk>/', BookingStatusUpdateView.as_view(), name='booking_status_update'),

    path('cars_list', CarsListView.as_view(), name='cars_list'),
    path('car/<int:pk>', CarsDetailView.as_view(), name='car_detail'),
    path('car_create/', CarsCreateView.as_view(), name='car_create'),
    path('car_update/<int:pk>', CarsUpdateView.as_view(), name='car_update'),
    path('car_delete/<int:pk>', CarsDeleteView.as_view(), name='car_delete'),

    path('request_create/', User_requestCreateView.as_view(), name='request_create'),
    path('request_list/', User_requestListView.as_view(), name='request_list'),
    path('request_update/<int:pk>', User_requestUpdateView.as_view(), name='request_update'),

    path('info/', info, name='info'),

    path('send_feedback/', send_feedback, name='send_feedback'),
    path('user-requests/update/<int:pk>/', User_requestStatusUpdateView.as_view(), name='request_status_update'),
    path('booking_create/', BookingCreateView.as_view(), name='booking_create')
]

news/urls.py
from django.urls import path
from news.apps import NewsConfig
from news.views import NewsCreateView, NewsListView, NewsDetailView, NewsUpdateView, NewsDeleteView

app_name = NewsConfig.name

urlpatterns = [
    path('create/', NewsCreateView.as_view(), name='create'),
    path('', NewsListView.as_view(), name='list'),
    path('view/<slug>/', NewsDetailView.as_view(), name='view'),
    path('edit/<slug>/', NewsUpdateView.as_view(), name='edit'),
    path('delete/<slug>', NewsDeleteView.as_view(), name='delete')

]

news/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class News(models.Model):
    """Модель новости"""
    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='news_pics/', verbose_name='изображение', **NULLABLE)
    date = models.DateField(auto_now=True, verbose_name='дата создания')

    def __str__(self):
        return f'{self.title}, дата публикации {self.date}'

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"

news/views.py
from django.conf import settings
from django.core.mail import send_mail

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

import news
from news.models import News
from pytils.translit import slugify
from telegram import Bot
from users.models import User


class NewsCreateView(CreateView):
    """Контроллер создания новости"""
    model = News
    fields = ('title', 'body', 'preview', )
    success_url = reverse_lazy('news:list')

    def form_valid(self, form):
        """ Добавляем слаг для формирования удобной ссылки на новость"""
        if form.is_valid():
            self.object = form.save()
            self.object.slug = slugify(self.object.title) # создание уникального slug идентификатора новости
            self.object.save()

            # Отправка сообщения в телеграм

            users = User.objects.filter(get_updates=True)

            for user in users:
                if user.get_updates:
                    send_mail(
                        subject=f"ДЦ Астор: {self.object.title}",
                        message=f"{self.object.body}",
                        from_email=settings.EMAIL_HOST_USER,
                        recipient_list=[user.email]
                    )


        return super().form_valid(form)


class NewsListView(ListView):
    """Контроллер просмотра списка новостей"""
    model = News


class NewsUpdateView(UpdateView):
    """Контроллер изменения отдельной новости"""
    model = News
    fields = ('title', 'body', 'preview',)
    success_url = reverse_lazy('news:list')

    def form_valid(self, form):
        """ Корректируем слаг для формирования удобной ссылки на новость"""
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.slug = slugify(self.object.title)  # Автоматическое обновление slug
            self.object.save()
            return super().form_valid(form)

    def get_success_url(self):
        return reverse('news:view', kwargs={'slug': self.object.slug})


class NewsDetailView(DetailView):
    """Контроллер просмотра отдельной новости"""
    model = News


class NewsDeleteView(DeleteView):
    """Контроллер удаления отдельной новости"""
    model = News
    success_url = reverse_lazy('news:list')

news/templates/news/news_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
               <div class="card-body">
                   <form method="post">
                       {% csrf_token %}
                       <p>Хотите удалить материал "{{ object.title }}"?</p>

                       <button type="submit" class="btn btn-danger">Подтверждение удаления</button>
                       <a href="{% url 'news:list' %}" class="btn btn-custom">Отмена</a>


                   </form>
               </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

news/templates/news/news_detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block content%}

    <div class="container">
        <div class="row">
            {% if object.preview %}

            <div class="col-md-4">
                <img style='max-width:300px' src="/media/{{ object.preview }}" alt="Новостная картинка">
            </div>
            {% endif %}


            <div class="col-md-8">
                <h2>{{ object.title }}</h2>
                <h5>{{ object.date }} </h5>
            </div>
            <div class="card-body">
            <p style="word-wrap: break-word;">{{ object.body }}</p>
            </div>



        </div>
    </div>
{% endblock %}

news/templates/news/news_form.html
{% extends 'main/base.html' %}
{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
               <div class="card-body">
                   <form method="post" enctype="multipart/form-data">
                       {% csrf_token %}
                       {{ form.as_p }}
                       <button type="submit" class="btn btn-custom">
                           {% if object %}
                                Сохранить
                           {% else %}
                                Создать
                           {% endif %}
                       </button>

                   </form>
               </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

news/templates/news/news_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Новости и объявления</h1>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-custom" href="{% url 'news:create' %}">Добавить новость</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {{ object.title }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'news:view' object.slug %}"
                       class="btn btn-custom">Посмотреть</a>
                    {% if user.is_staff %}
                    <a href="{% url 'news:edit' object.slug %}"
                       class="btn btn-custom">Редактировать</a>
                    <a href="{% url 'news:delete' object.slug %}"
                       class="btn btn-custom">Удалить</a>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}