announcements/urls.py
from django.urls import path
from announcements.apps import AnnouncementsConfig
from announcements.views import (AnnouncementsListView, AnnouncementsDetailView,
                                 AnnouncementsUpdateView, AnnouncementsDeleteView, AnnouncementsCreateView)

app_name = AnnouncementsConfig.name

urlpatterns = [
    path('', AnnouncementsListView.as_view(), name='list'),
    path('create/', AnnouncementsCreateView.as_view(), name='create'),
    path('view/<slug>/', AnnouncementsDetailView.as_view(), name='view'),
    path('edit/<slug>/', AnnouncementsUpdateView.as_view(), name='edit'),
    path('delete/<slug>', AnnouncementsDeleteView.as_view(), name='delete')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('news/', include('news.urls', namespace='news')),
    path('announcements/', include('announcements.urls', namespace='announcements')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.apps import MainConfig
from main.views import (CompanyListView, CompanyDetailView,
                        CompanyCreateView, CompanyUpdateView, IndexView,
                        OfficeListView, OfficeDetailView, OfficeCreateView,
                        OfficeUpdateView, contacts, CompanyDeleteView,
                        OfficeDeleteView, BookingCreateView, CarsListView, CarsDetailView,
                        CarsCreateView, CarsUpdateView, CarsDeleteView, User_requestCreateView, User_requestListView,
                        User_requestDetailView, User_requestDeleteView, User_requestUpdateView, info, send_feedback,
                        User_requestStatusUpdateView, BookingListView, BookingUpdateView, BookingStatusUpdateView)

app_name = MainConfig.name

urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('contacts/', contacts, name='contacts'),
    path('company_list', CompanyListView.as_view(), name='labtest_list'),
    path('company/<int:pk>', CompanyDetailView.as_view(), name='labtest_detail'),
    path('company_create/', CompanyCreateView.as_view(), name='labtest_create'),
    path('company_update/<int:pk>', CompanyUpdateView.as_view(), name='labtest_update'),
    path('company_delete/<int:pk>', CompanyDeleteView.as_view(), name='labtest_delete'),

    path('office_list', OfficeListView.as_view(), name='office_list'),
    path('office/<int:pk>', OfficeDetailView.as_view(), name='office_detail'),
    path('office_create/', OfficeCreateView.as_view(), name='office_create'),
    path('office_update/<int:pk>', OfficeUpdateView.as_view(), name='office_update'),
    path('office_delete/<int:pk>', OfficeDeleteView.as_view(), name='office_delete'),

    path('booking_create/', BookingCreateView.as_view(), name='booking_create'),
    path('booking_list', BookingListView.as_view(), name='booking_list'),
    path('booking_update/<int:pk>', BookingUpdateView.as_view(), name='booking_update'),
    path('booking/update/<int:pk>/', BookingStatusUpdateView.as_view(), name='booking_status_update'),

    path('cars_list', CarsListView.as_view(), name='cars_list'),
    path('car/<int:pk>', CarsDetailView.as_view(), name='car_detail'),
    path('car_create/', CarsCreateView.as_view(), name='car_create'),
    path('car_update/<int:pk>', CarsUpdateView.as_view(), name='car_update'),
    path('car_delete/<int:pk>', CarsDeleteView.as_view(), name='car_delete'),

    path('request_create/', User_requestCreateView.as_view(), name='request_create'),
    path('request_list/', User_requestListView.as_view(), name='request_list'),
    path('request_update/<int:pk>', User_requestUpdateView.as_view(), name='request_update'),

    path('info/', info, name='info'),

    path('send_feedback/', send_feedback, name='send_feedback'),
    path('user-requests/update/<int:pk>/', User_requestStatusUpdateView.as_view(), name='request_status_update'),
    path('booking_create/', BookingCreateView.as_view(), name='booking_create')
]

announcements/models.py
from django.db import models
from django.utils import timezone

from django.conf import settings
from pytils.translit import slugify


class Announcement(models.Model):
    """Модель объявлений, подаваемых арендаторами"""
    title = models.CharField(max_length=200, verbose_name='Заголовок объявления (будет видим на главной странице)')
    body = models.TextField(verbose_name='Текст объявления', null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name='Активно')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    image = models.ImageField(upload_to='announcements', verbose_name='Изображение', null=True, blank=True)
    stop_date = models.DateField(verbose_name='Дата окончания показа объявления',
                                 default=timezone.now() + timezone.timedelta(days=30))
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              verbose_name='арендатор',
                              null=True, blank=True)
    slug = models.CharField(max_length=100, verbose_name='slug', null=True, blank=True)




    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'

announcements/forms.py
from django import forms
from announcements.models import Announcement


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class AnnouncementForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Announcement
        fields = ('title', 'body', 'image', 'stop_date')
        widgets = {

           'stop_date': forms.DateInput(attrs={'type': 'date'}),
        }

announcements/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from pytils.translit import slugify

from announcements.forms import AnnouncementForm
from announcements.models import Announcement


class AnnouncementsCreateView(CreateView):
    """Контроллер создания объявления"""
    model = Announcement
    form_class = AnnouncementForm

    def form_valid(self, form):
        """ Добавляем слаг для формирования удобной ссылки на объявление"""
        if form.is_valid():
            self.object = form.save()
            self.object.slug = slugify(self.object.title) # создание уникального slug идентификатора новости
            self.object.owner = self.request.user
            self.object.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('announcements:view', kwargs={'slug': self.object.slug})


class AnnouncementsListView(ListView):
    """Контроллер просмотра списка новостей"""
    model = Announcement
    ordering = ['-created_at']


class AnnouncementsUpdateView(UpdateView):
    """Контроллер изменения отдельной новости"""
    model = Announcement
    fields = ('title', 'body', 'image', 'is_active', 'stop_date')
    success_url = reverse_lazy('announcements:view')

    def form_valid(self, form):
        """ Корректируем слаг для формирования удобной ссылки на новость"""
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.slug = slugify(self.object.title)  # Автоматическое обновление slug
            self.object.save()
            return super().form_valid(form)

    def get_success_url(self):
        return reverse('news:view', kwargs={'slug': self.object.slug})


class AnnouncementsDetailView(DetailView):
    """Контроллер просмотра отдельной новости"""
    model = Announcement


class AnnouncementsDeleteView(DeleteView):
    """Контроллер удаления отдельной новости"""
    model = Announcement
    success_url = reverse_lazy('main:index')

announcements/templates/announcements/announcement_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
               <div class="card-body">
                   <form method="post">
                       {% csrf_token %}
                       <p>Хотите удалить материал "{{ object.title }}"?</p>

                       <button type="submit" class="btn btn-custom">Подтверждение удаления</button>
                       <a href="{% url 'news:list' %}" class="btn btn-warning">Отмена</a>


                   </form>
               </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

announcements/templates/announcements/announcement_detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block content%}

    <div class="container">
        <div class="row">

            <div class="col-md-4">
                <img style='max-width:300px' src="/media/{{ object.image }}" alt="Новостная картинка">
            </div>


            <div class="col-md-8">
                <h2>{{ object.title }}</h2>
                <h5>{{ object.date }} </h5>
            </div>
            <div class="card-body">
            <p style="word-wrap: break-word;">{{ object.body }}</p>
            </div>



        </div>
    </div>
    {% if is_owner %}
    <a href="{% url 'announcements:edit' object.slug %}" class="btn btn-custom">Изменить</a>
        <a href="{% url 'announcements:delete' object.slug %}" class="btn btn-custom">Удалить</a>
    {% endif %}

{% endblock %}

announcements/templates/announcements/announcement_form.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
               <div class="card-body">
               <p>Не забудьте указать название компании и к кому обращаться. Ваши данные, указанные при регистрации на сайте, останутся скрытыми.</p>
                   <form method="post" enctype="multipart/form-data">
                       {% csrf_token %}
                       {{ form.as_p }}
                       <button type="submit" class="btn btn-custom">
                           {% if object %}
                                Сохранить
                           {% else %}
                                Создать
                           {% endif %}
                       </button>

                   </form>
               </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

announcements/templates/announcements/announcement_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Объявления и акции от арендаторов ДЦ Астор</h1>
</div>
<div class="col-12 mb-5">

</div>
{% for object in object_list %}
<div class="col-md-offset-12">
                                    <p><b> {{ object.title }}</b></p>
                                  <p>{{ object.body }}</p>
                              <p>
                          </div>
                                      {% if not loop.last %}
            <hr>
    {% endif %}
{% endfor %}
    {% if user.is_authenticated %}
    <a class="btn btn-custom" href="{% url 'announcements:create' %}">Добавить свое объявление</a>
{% endif %}
    <p></p>
     <p></p>
     <p></p>
     <p></p>

{% endblock %}