config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('news/', include('news.urls', namespace='news')),
    path('announcements/', include('announcements.urls', namespace='announcements')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.apps import MainConfig
from main.views import (CompanyListView, CompanyDetailView,
                        CompanyCreateView, CompanyUpdateView, IndexView,
                        OfficeListView, OfficeDetailView, OfficeCreateView,
                        OfficeUpdateView, contacts, CompanyDeleteView,
                        OfficeDeleteView, BookingCreateView, CarsListView, CarsDetailView,
                        CarsCreateView, CarsUpdateView, CarsDeleteView, User_requestCreateView, User_requestListView,
                        User_requestDetailView, User_requestDeleteView, User_requestUpdateView, info, send_feedback,
                        User_requestStatusUpdateView, BookingListView, BookingUpdateView, BookingStatusUpdateView)

app_name = MainConfig.name

urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('contacts/', contacts, name='contacts'),
    path('company_list', CompanyListView.as_view(), name='labtest_list'),
    path('company/<int:pk>', CompanyDetailView.as_view(), name='labtest_detail'),
    path('company_create/', CompanyCreateView.as_view(), name='labtest_create'),
    path('company_update/<int:pk>', CompanyUpdateView.as_view(), name='labtest_update'),
    path('company_delete/<int:pk>', CompanyDeleteView.as_view(), name='labtest_delete'),

    path('office_list', OfficeListView.as_view(), name='office_list'),
    path('office/<int:pk>', OfficeDetailView.as_view(), name='office_detail'),
    path('office_create/', OfficeCreateView.as_view(), name='office_create'),
    path('office_update/<int:pk>', OfficeUpdateView.as_view(), name='office_update'),
    path('office_delete/<int:pk>', OfficeDeleteView.as_view(), name='office_delete'),

    path('booking_create/', BookingCreateView.as_view(), name='booking_create'),
    path('booking_list', BookingListView.as_view(), name='booking_list'),
    path('booking_update/<int:pk>', BookingUpdateView.as_view(), name='booking_update'),
    path('booking/update/<int:pk>/', BookingStatusUpdateView.as_view(), name='booking_status_update'),

    path('cars_list', CarsListView.as_view(), name='cars_list'),
    path('car/<int:pk>', CarsDetailView.as_view(), name='car_detail'),
    path('car_create/', CarsCreateView.as_view(), name='car_create'),
    path('car_update/<int:pk>', CarsUpdateView.as_view(), name='car_update'),
    path('car_delete/<int:pk>', CarsDeleteView.as_view(), name='car_delete'),

    path('request_create/', User_requestCreateView.as_view(), name='request_create'),
    path('request_list/', User_requestListView.as_view(), name='request_list'),
    path('request_update/<int:pk>', User_requestUpdateView.as_view(), name='request_update'),

    path('info/', info, name='info'),

    path('send_feedback/', send_feedback, name='send_feedback'),
    path('user-requests/update/<int:pk>/', User_requestStatusUpdateView.as_view(), name='request_status_update'),
    path('booking_create/', BookingCreateView.as_view(), name='booking_create')
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, UserDetailView, UserLoginView

app_name = UsersConfig.name
urlpatterns = [
    path('', UserLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('user_detail/<int:pk>', UserDetailView.as_view(), name='user_detail'),

]

main/models.py
import datetime

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from users.models import User


class Company(models.Model):
    name = models.CharField(max_length=50, verbose_name='название категории')
    description = models.TextField(verbose_name='описание')
    logo = models.ImageField(upload_to='logos/',
                             verbose_name='логотип', null=True, blank=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'


class Office(models.Model):
    office_id = models.CharField(max_length=100, verbose_name='помещение', unique=True)
    floor = models.IntegerField(verbose_name='этаж')
    sq_m = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='площадь')
    image1 = models.ImageField(upload_to='offices/', verbose_name='фото', null=True, blank=True)
    image2 = models.ImageField(upload_to='offices/',
                               verbose_name='фото', null=True, blank=True)
    image3 = models.ImageField(upload_to='offices/',
                               verbose_name='фото', null=True, blank=True)
    description = models.TextField(verbose_name='описание',
                                   null=True, blank=True)
    price = models.IntegerField(verbose_name='цена',
                                null=True, blank=True)

    def __str__(self):
        return f'{self.office_id}'

    class Meta:
        verbose_name = 'Помещение'
        verbose_name_plural = 'Помещения'
        ordering = ('office_id',)


class User_request(models.Model):
    URGENT = 'срочно'
    NOT_URGENT = 'в текущем режиме'
    URGENCY = (
        (URGENT, 'срочно'),
        (NOT_URGENT, 'в текущем режиме')
    )

    DONE = 'выполнено'
    IN_PROGRESS = 'в работе'
    CLOSED = 'завершено'
    STATUS = ((DONE, 'выполнено'), (IN_PROGRESS, 'в работе'), (CLOSED, 'завершено'))

    date = models.DateTimeField(default=timezone.now, verbose_name='дата и время заявки')
    office_id = models.CharField(max_length=100, verbose_name='помещение')
    owner = models.ForeignKey(User, on_delete=models.CASCADE,
                              verbose_name='отправитель')
    description = models.TextField(verbose_name='описание')
    urgency = models.CharField(max_length=20, choices=URGENCY,
                               default=NOT_URGENT, verbose_name='срочность')
    status = models.CharField(max_length=20, choices=STATUS,
                              default=IN_PROGRESS, verbose_name='статус')
    comments = models.TextField(verbose_name='комментарий', blank=True, null=True)
    feedback = models.TextField(verbose_name='комментарий отправителя заявки', blank=True, null=True)
    date_completed = models.DateTimeField(verbose_name='дата и время выполнения заявки', blank=True, null=True)


    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'
        ordering = ('-date',)

    def __str__(self):
        return f'{self.description}'


class Booking(models.Model):
    TIMESLOT_LIST = (
        (0, 'первая половина дня'),
        (1, 'вторая половина дня'),
        (2, 'весь день'),

    )

    APPROVED = 'Согласовано'
    IN_PROGRESS = 'Отправлено на согласование'
    STATUS = ((APPROVED, 'Согласовано'), (IN_PROGRESS, 'Отправлено на согласование'))


    date = models.DateField(default=timezone.now, verbose_name='дата')

    duration = models.IntegerField(choices=TIMESLOT_LIST,
                                   verbose_name='длительность')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                              verbose_name='арендатор',
                              null=True, blank=True)
    status = models.CharField(max_length=100, choices=STATUS,
                              default=IN_PROGRESS, verbose_name='статус')

    comment = models.TextField(verbose_name='комментарий', null=True, blank=True)

    def __str__(self):
        return (f' Бронь переговорки:{self.date}, '
                f'от арендатора {self.owner}')


    class Meta:
        verbose_name = 'Бронь переговорки'
        verbose_name_plural = 'Брони переговорки'


class Cars(models.Model):
    ONE_TIME = 'разовый'
    PERMANENT = 'на постоянной основе'
    PERIOD = ((ONE_TIME, 'разовый'),

              (PERMANENT, 'на постоянной основе'))

    APPROVED = 'Согласовано'
    IN_PROGRESS = 'Отправлено на согласование'
    STATUS = ((APPROVED, 'Согласовано'), (IN_PROGRESS, 'Отправлено на согласование'))

    car_id = models.CharField(max_length=100, verbose_name='номер авто', unique=True)
    model = models.CharField(max_length=100, verbose_name='модель')
    period = models.CharField(max_length=20, choices=PERIOD,
                              default=PERMANENT, verbose_name='Или период выдачи разрешения на доступ')
    start_date = models.DateField(default=datetime.date.today, verbose_name='Выберите дату начала доступа')
    end_date = models.DateField(verbose_name='Выберите дату окончания доступа', blank=True, null=True)
    status = models.CharField(max_length=100, choices=STATUS,
                              default=IN_PROGRESS, verbose_name='статус')
    price = models.IntegerField(verbose_name='цена',
                                null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              verbose_name='арендатор',
                              null=True, blank=True)

    def __str__(self):
        return f'{self.car_id}, {self.owner}'

    class Meta:
        verbose_name = 'Допуск авто'
        verbose_name_plural = 'Допуски авто'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None

    email = models.EmailField(verbose_name='почта', unique=True)
    office_number = models.IntegerField(verbose_name='номер помещения', null=True, blank=True)
    company = models.CharField(max_length=50, verbose_name='компания', null=True, blank=True)
    name = models.CharField(max_length=50, verbose_name='имя', null=True, blank=True)
    phone = models.CharField(max_length=20, verbose_name='телефон', null=True, blank=True)
    is_staff = models.BooleanField(default=False, verbose_name='Сотрудник')
    is_manager = models.BooleanField(default=False, verbose_name='Менеджер')
    tg_account = models.CharField(max_length=50, verbose_name='аккаунт в telegram', null=True, blank=True)
    get_updates = models.BooleanField(default=False, verbose_name='Получать уведомления на почту')
    get_updates_tg = models.BooleanField(default=False, verbose_name='Получать уведомления на telegram')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms
from django.core.exceptions import ValidationError
from django.utils.crypto import get_random_string
from main.forms import StyleFormMixin
from users.models import User


class UserLoginForm(StyleFormMixin, AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ["email", "name", "office_number", "company", "phone",
                  "get_updates", "password1", "password2"]

    def save(self, commit=True):
        user = super().save(commit=False)
        user.save()
        return user


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ["email", "name", "office_number", "company", "phone"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class UserLoginForm(StyleFormMixin, AuthenticationForm):
    """Форма для контроля авторизации пользователей с подтвержденным почтовым адресом"""

    def clean(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if email and password:
            user = authenticate(username=email, password=password)  # аутентификация пользователя по email

            if user and not user.is_active:
                raise ValidationError('Вам нужно подтвердить свой почтовый адрес, прежде чем войти.')

        return super().clean()

users/views.py
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView, DetailView

from main.models import User_request, Cars, Booking
from users.forms import UserRegisterForm, UserForm, UserLoginForm
from users.models import User


class UserLoginView(LoginView):
    model = User
    template_name = 'users/login.html'
    form_class = UserLoginForm


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'


class ProfileView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserDetailView(DetailView):
    model = User
    context_object_name = 'object_user'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()

        user_requests = User_request.objects.filter(owner=user)
        for request in user_requests:
            self.check_request_status(request)
        context['user_requests'] = user_requests

        cars = Cars.objects.filter(owner=user)
        context['cars'] = cars

        booking = Booking.objects.filter(owner=user)
        context['bookings'] = booking

        # Проверяем, является ли текущий пользователь владельцем страницы
        is_owner = self.request.user == user
        context['is_owner'] = is_owner

        return context

    def check_request_status(self, request):
        if request.date_completed and request.status == 'выполнено':

            one_week_ago = timezone.now() - timezone.timedelta(weeks=1)
            if request.date_completed < one_week_ago:
                request.status = 'завершено'
                request.save()

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content%}

        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">

                <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            Вход
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-custom">Войти</button>

                </div>
            </div>
        </div>

    </form>
        <a href="{% url 'password_reset' %}">Забыли Ваш пароль?</a>
        </div>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <h4>Запрос на восстановление пароля на сайте</h4>
                 </div>
           </div>


        <div class="card-body">
                <p>Введите адрес электронной почты, связанный с вашей учетной записью, и мы отправим вам ссылку для сброса пароля.</p>

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-custom">Восстановить пароль</button>
            </form>
        </div>
    </div>
    </div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="card-title">
     <h1>Восстановление пароля завершено</h1>
                    </div>
           </div>
<div class="card-body">
    <p>Ваш пароль был сохранен.</p>
    <p>Теперь Вы можете <a href="{% url 'users:login' %}">войти</a> с Вашим новым паролем.</p>

</div>
    {% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="card-title">
    <h2>Подтверждение сброса пароля</h2>
                  </div>
           </div>

<div class="card-body">
  {% if validlink %}
<p>Введите новый пароль, чтобы завершить сброс пароля.</p>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Сохранить пароль</button>
    </form>
  {% else %}
    <p>Ссылка для сброса пароля недействительна или истекла.</p>
  {% endif %}
          </form>
        </div>
    </div>
    </div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-6">
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <h4>Письмо с инструкциями по восстановлению пароля отправлено</h4>
                 </div>
           </div>
        <div class="card-body">
                <p>Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты (если в нашей базе данных есть такой адрес). Вы должны получить ее в ближайшее время.</p>

                <p>Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.</p>
            </div>

        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}

{% block content%}

        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="col-3"></div>
                <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-custom">Регистрация</button>
                </div>
            </div>
        </div>

    </form>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'main/base.html' %}
{% block content %}

    <div class="container">
        {% if is_owner %}
            <div class="row mt-4 mb-4">

            </div>
        {% endif %}

        <!-- часть с информацией о юзере -->
        <div class="col-md-9">
            <p><b>Имя:</b> {{ object_user.name }} </p>
            <p><b>Электронная почта:</b> {{ object_user.email }} </p>
            <p><b>Офис:</b> {{ object_user.office_number }} </p>
            <p><b>Компания:</b> {{ object_user.company }}</p>
            <p><b>Телефон для связи:</b> {{ object_user.phone }}</p>


        </div>




        {% if is_owner %}
            <div class="col-md-12">
                <a href="{% url 'users:profile' %}" class="btn btn-custom">Редактировать профиль</a>
                <a href="{% url 'main:request_create' %}" class="btn btn-custom">Создать заявку</a>

                <a href="{% url 'main:car_create' %}" class="btn btn-custom">Запросить доступ на территорию</a></div>
        {% endif %}
        <div class="col-md-12 border p-3 m-3">

            {% if user_requests %}
                <h2 class="bg-secondary text-light p-2">Ваши заявки*</h2>
                <p> *Здесь Вы видите Ваши заявки. Вы можете отправить замечание исполнителю, если качество выполнения
                    заявки Вас не устроило, и статус заявки меняется на "в работе". Если замечания не отправлены в
                    течение 5 дней после выполнения заявки и изменения статуса на "выполнено", заявка считается
                    выполненной и закрывается.</p>
                {% for req in user_requests %}
                    <div class="col-md-offset-12">
                        <p><b>Дата:</b> {{ req.date }}</p>
                        <p><b>Офис:</b> {{ req.office_id }}</p>
                        <p><b>Описание:</b> {{ req.description }}</p>
                        <p><b>Статус:</b> {{ req.status }}</p>
                        {% if req.comments %}
                            <p><b>Комментарий исполнителя:</b> {{ req.comments }}</p>
                        {% endif %}
                        {% if req.feedback %}
                            <p><b>Комментарий отправителя заявки:</b> {{ req.feedback }}</p>
                        {% endif %}
                        {% if req.status != 'завершено' %}
                            <form method="POST" action="{% url 'main:send_feedback' %}">
                                {% csrf_token %}
                                <input type="hidden" name="request_id" value="{{ req.id }}">
                                <textarea name="feedback"></textarea>
                                <p>
                                    <button type="submit" class="btn btn-custom">Отправить замечания</button>
                                </p>
                            </form>
                        {% else %}
                            <p>Заявка закрыта</p>
                        {% endif %}

                    </div>
                    {% if not loop.last %}
                        <hr>
                    {% endif %}

                {% endfor %}
            {% else %}
                <p>У вас пока нет отправленных заявок в Службу Эксплуатаци</p>
            {% endif %}


            <h2 class="bg-secondary text-light p-2">Доступ автомобилей на территорию</h2>
            {% if cars %}
                {% for car in cars %}
                    <div class="col-md-offset-12">

                        <p><b>Номер авто</b> {{ car.car_id }}</p>
                        <p><b>Модель</b> {{ car.model }}</p>
                        <p><b>Статус запроса</b> {{ car.status }}</p>
                    </div>
                    {% if not loop.last %}
                        <hr>
                    {% endif %}

                {% endfor %}
            {% else %}
                <p>У вас пока нет запросов на доступ авто на территорию</p>
            {% endif %}
            <h2 class="bg-secondary text-light p-2">Бронирование переговорки</h2>
            {% if cars %}
                {% for booking in bookings %}
                    <div class="col-md-offset-12">

                        <p><b>Дата</b> {{ booking.date }}</p>
                        <p><b>Время</b> {{ booking.get_duration_display }}</p>
                        <p><b>Статус запроса</b> {{ booking.status }}</p>
                    </div>
                    {% if not loop.last %}
                        <hr>
                    {% endif %}

                {% endfor %}
            {% else %}
                <p>У вас пока нет бронирований переговорки</p>
            {% endif %}

        </div>
    </div>
    </div>
    </div>
    </div>
    </div>

    </div>



{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row mt-5">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h6>Профиль пользователя</h6>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-custom">Сохранить</button>
                </form>
            </div>
            <div class="card-footer">

            </div>
        </div>
    </div>
</div>

{% endblock %}