config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('news/', include('news.urls', namespace='news')),
    path('announcements/', include('announcements.urls', namespace='announcements')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.apps import MainConfig
from main.views import (CompanyListView, CompanyDetailView,
                        CompanyCreateView, CompanyUpdateView, IndexView,
                        OfficeListView, OfficeDetailView, OfficeCreateView,
                        OfficeUpdateView, contacts, CompanyDeleteView,
                        OfficeDeleteView, BookingCreateView, CarsListView, CarsDetailView,
                        CarsCreateView, CarsUpdateView, CarsDeleteView, User_requestCreateView, User_requestListView,
                        User_requestDetailView, User_requestDeleteView, User_requestUpdateView, info, send_feedback,
                        User_requestStatusUpdateView, BookingListView, BookingUpdateView, BookingStatusUpdateView)

app_name = MainConfig.name

urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('contacts/', contacts, name='contacts'),
    path('company_list', CompanyListView.as_view(), name='labtest_list'),
    path('company/<int:pk>', CompanyDetailView.as_view(), name='labtest_detail'),
    path('company_create/', CompanyCreateView.as_view(), name='labtest_create'),
    path('company_update/<int:pk>', CompanyUpdateView.as_view(), name='labtest_update'),
    path('company_delete/<int:pk>', CompanyDeleteView.as_view(), name='labtest_delete'),

    path('office_list', OfficeListView.as_view(), name='office_list'),
    path('office/<int:pk>', OfficeDetailView.as_view(), name='office_detail'),
    path('office_create/', OfficeCreateView.as_view(), name='office_create'),
    path('office_update/<int:pk>', OfficeUpdateView.as_view(), name='office_update'),
    path('office_delete/<int:pk>', OfficeDeleteView.as_view(), name='office_delete'),

    path('booking_create/', BookingCreateView.as_view(), name='booking_create'),
    path('booking_list', BookingListView.as_view(), name='booking_list'),
    path('booking_update/<int:pk>', BookingUpdateView.as_view(), name='booking_update'),
    path('booking/update/<int:pk>/', BookingStatusUpdateView.as_view(), name='booking_status_update'),

    path('cars_list', CarsListView.as_view(), name='cars_list'),
    path('car/<int:pk>', CarsDetailView.as_view(), name='car_detail'),
    path('car_create/', CarsCreateView.as_view(), name='car_create'),
    path('car_update/<int:pk>', CarsUpdateView.as_view(), name='car_update'),
    path('car_delete/<int:pk>', CarsDeleteView.as_view(), name='car_delete'),

    path('request_create/', User_requestCreateView.as_view(), name='request_create'),
    path('request_list/', User_requestListView.as_view(), name='request_list'),
    path('request_update/<int:pk>', User_requestUpdateView.as_view(), name='request_update'),

    path('info/', info, name='info'),

    path('send_feedback/', send_feedback, name='send_feedback'),
    path('user-requests/update/<int:pk>/', User_requestStatusUpdateView.as_view(), name='request_status_update'),
    path('booking_create/', BookingCreateView.as_view(), name='booking_create')
]

news/urls.py
from django.urls import path
from news.apps import NewsConfig
from news.views import NewsCreateView, NewsListView, NewsDetailView, NewsUpdateView, NewsDeleteView

app_name = NewsConfig.name

urlpatterns = [
    path('create/', NewsCreateView.as_view(), name='create'),
    path('', NewsListView.as_view(), name='list'),
    path('view/<slug>/', NewsDetailView.as_view(), name='view'),
    path('edit/<slug>/', NewsUpdateView.as_view(), name='edit'),
    path('delete/<slug>', NewsDeleteView.as_view(), name='delete')

]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, UserDetailView, UserLoginView

app_name = UsersConfig.name
urlpatterns = [
    path('', UserLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('user_detail/<int:pk>', UserDetailView.as_view(), name='user_detail'),

]

main/models.py
import datetime

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from users.models import User


class Company(models.Model):
    name = models.CharField(max_length=50, verbose_name='название категории')
    description = models.TextField(verbose_name='описание')
    logo = models.ImageField(upload_to='logos/',
                             verbose_name='логотип', null=True, blank=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'


class Office(models.Model):
    office_id = models.CharField(max_length=100, verbose_name='помещение', unique=True)
    floor = models.IntegerField(verbose_name='этаж')
    sq_m = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='площадь')
    image1 = models.ImageField(upload_to='offices/', verbose_name='фото', null=True, blank=True)
    image2 = models.ImageField(upload_to='offices/',
                               verbose_name='фото', null=True, blank=True)
    image3 = models.ImageField(upload_to='offices/',
                               verbose_name='фото', null=True, blank=True)
    description = models.TextField(verbose_name='описание',
                                   null=True, blank=True)
    price = models.IntegerField(verbose_name='цена',
                                null=True, blank=True)

    def __str__(self):
        return f'{self.office_id}'

    class Meta:
        verbose_name = 'Помещение'
        verbose_name_plural = 'Помещения'
        ordering = ('office_id',)


class User_request(models.Model):
    URGENT = 'срочно'
    NOT_URGENT = 'в текущем режиме'
    URGENCY = (
        (URGENT, 'срочно'),
        (NOT_URGENT, 'в текущем режиме')
    )

    DONE = 'выполнено'
    IN_PROGRESS = 'в работе'
    CLOSED = 'завершено'
    STATUS = ((DONE, 'выполнено'), (IN_PROGRESS, 'в работе'), (CLOSED, 'завершено'))

    date = models.DateTimeField(default=timezone.now, verbose_name='дата и время заявки')
    office_id = models.CharField(max_length=100, verbose_name='помещение')
    owner = models.ForeignKey(User, on_delete=models.CASCADE,
                              verbose_name='отправитель')
    description = models.TextField(verbose_name='описание')
    urgency = models.CharField(max_length=20, choices=URGENCY,
                               default=NOT_URGENT, verbose_name='срочность')
    status = models.CharField(max_length=20, choices=STATUS,
                              default=IN_PROGRESS, verbose_name='статус')
    comments = models.TextField(verbose_name='комментарий', blank=True, null=True)
    feedback = models.TextField(verbose_name='комментарий отправителя заявки', blank=True, null=True)
    date_completed = models.DateTimeField(verbose_name='дата и время выполнения заявки', blank=True, null=True)


    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'
        ordering = ('-date',)

    def __str__(self):
        return f'{self.description}'


class Booking(models.Model):
    TIMESLOT_LIST = (
        (0, 'первая половина дня'),
        (1, 'вторая половина дня'),
        (2, 'весь день'),

    )

    APPROVED = 'Согласовано'
    IN_PROGRESS = 'Отправлено на согласование'
    STATUS = ((APPROVED, 'Согласовано'), (IN_PROGRESS, 'Отправлено на согласование'))


    date = models.DateField(default=timezone.now, verbose_name='дата')

    duration = models.IntegerField(choices=TIMESLOT_LIST,
                                   verbose_name='длительность')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                              verbose_name='арендатор',
                              null=True, blank=True)
    status = models.CharField(max_length=100, choices=STATUS,
                              default=IN_PROGRESS, verbose_name='статус')

    comment = models.TextField(verbose_name='комментарий', null=True, blank=True)

    def __str__(self):
        return (f' Бронь переговорки:{self.date}, '
                f'от арендатора {self.owner}')


    class Meta:
        verbose_name = 'Бронь переговорки'
        verbose_name_plural = 'Брони переговорки'


class Cars(models.Model):
    ONE_TIME = 'разовый'
    PERMANENT = 'на постоянной основе'
    PERIOD = ((ONE_TIME, 'разовый'),

              (PERMANENT, 'на постоянной основе'))

    APPROVED = 'Согласовано'
    IN_PROGRESS = 'Отправлено на согласование'
    STATUS = ((APPROVED, 'Согласовано'), (IN_PROGRESS, 'Отправлено на согласование'))

    car_id = models.CharField(max_length=100, verbose_name='номер авто', unique=True)
    model = models.CharField(max_length=100, verbose_name='модель')
    period = models.CharField(max_length=20, choices=PERIOD,
                              default=PERMANENT, verbose_name='Или период выдачи разрешения на доступ')
    start_date = models.DateField(default=datetime.date.today, verbose_name='Выберите дату начала доступа')
    end_date = models.DateField(verbose_name='Выберите дату окончания доступа', blank=True, null=True)
    status = models.CharField(max_length=100, choices=STATUS,
                              default=IN_PROGRESS, verbose_name='статус')
    price = models.IntegerField(verbose_name='цена',
                                null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              verbose_name='арендатор',
                              null=True, blank=True)

    def __str__(self):
        return f'{self.car_id}, {self.owner}'

    class Meta:
        verbose_name = 'Допуск авто'
        verbose_name_plural = 'Допуски авто'

main/forms.py
from datetime import date

from django import forms
from .models import Company, Office, User_request, Booking, Cars


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CompanyForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Company
        fields = ('name', 'description', 'logo')


class OfficeForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Office
        fields = ('office_id', 'floor', 'sq_m', 'description', 'price')


class User_requestForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User_request
        fields = ('office_id', 'description', 'urgency', 'status', 'comments')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        if not self.request.user.is_staff:
            self.fields['comments'].widget = forms.HiddenInput()



class BookingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Booking
        fields = ('date', 'duration', 'status')
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

    def clean_date(self):
        day = self.cleaned_data['date']

        if day <= date.today():
            raise forms.ValidationError(
                'Выберите, пожалуйста, '
                'дату в будущем (завтра или позднее)',
                code='invalid'
            )
        return day


class CarsForm(StyleFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        if not self.request.user.is_manager:
            self.fields['price'].widget = forms.HiddenInput()
            self.fields['status'].widget = forms.HiddenInput()

    class Meta:
        model = Cars
        fields = ('car_id', 'model', 'start_date', 'end_date', 'period', 'status', 'price')
        widgets = {
            # Виджеты для даты
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
        }

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ДЦ Астор</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat+Display:700,900" rel="stylesheet">
    <link href="/static/css/blog.css" rel="stylesheet">
    <style>

  body {
      display: flex;
      flex-flow: column;
      min-height: 100vh;
    }

    .container {
      flex: 1;
    }
    .btn-custom {
    background-color: #FF4500; /* Установите нужный цвет в формате HEX */
    border-color: #FF4500;
    color: #ffffff; /* Установите цвет текста на кнопке */
}

.btn-custom:hover {
    background-color: #FF8C00; /* Изменение цвета кнопки при наведении */
    border-color: #FF8C00;
}
.hr-custom {
    border-top: 2px solid #FF4500; /* Установите нужный цвет в формате HEX */
}
    </style>
  </head>

  <body>

    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
              <img src="/media/logo_astor.jpg" width="110" height="100">
          </div>
          <div class="col-4 text-center">
            <h1>Торгово-деловой центр АСТОР</h1>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
           
             
            </a>
            <nav class="nav d-flex justify-content-between">
              {% if user.is_authenticated %}
                <div class="header">
                  <a class="btn btn-custom" href="{% url 'users:user_detail' pk=user.pk %}">Личный кабинет</a>
                  <form action="{% url 'users:logout' %}" method="post" class="d-inline">
                      {% csrf_token %}
                      <button type="submit"  class="btn btn-custom">Выйти</button>
                  </form>
                </div>
              {% else %}
                <div class="header">
                  <a class="btn btn-custom" href="{% url 'users:login' %}">Войти</a>
                  <a class="btn btn-custom" href="{% url 'users:register' %}">Регистрация</a>
                </div>
              {% endif %}
            </nav>
          </div>
        </div>
      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <a class="p-2 text-muted" href="{% url 'main:index' %}">ГЛАВНАЯ</a>
          <a class="p-2 text-muted" href="{% url 'main:info' %}">ДЦ "АСТОР"</a>         
          <a class="p-2 text-muted" href="#">СВОБОДНЫЕ ОФИСЫ</a>
         {% if user.is_authenticated %}
          <a class="p-2 text-muted" href="{% url 'main:booking_create' %}">БРОНИРОВАНИЕ ПЕРЕГОВОРКИ</a>
        {% else %}
        <a class="p-2 text-muted" href="{% url 'users:login' %}">БРОНИРОВАНИЕ ПЕРЕГОВОРКИ</a>
        {% endif %}
          
          <a class="p-2 text-muted" href="{% url 'main:contacts' %}">КОНТАКТЫ</a>
        </nav>
      </div>
<main class="flex-grow-1">
      {% block content %}
      {% endblock %}
</main>
    </div>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#"></a>
        </p>
        <p class="mb-2">Хайдукова&copy; {% now 'Y' %}</p>
      </div>
    </footer>

    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/holder.min.js"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  </body>
</html>

main/templates/main/booking_list.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}


<div class="container mt-5">
            <div class="row">
                <h3 class="text-left">Брони на согласование</h3>
               
                <table class="table">
                    <thead>
                    <tr>
                        <th>Дата мероприятия</th>
                        <th>Арендатор </th>
                        <th>Номер офиса </th>
                        <th>Телефон </th>
                        <th>Длительность</th>                        
                        <th>Статус заявки</th>
                        <th>Комментарий</th>
                      
                        
                        
                    </tr>
                    </thead>
                    <tbody>

                    {% for b in received_booking %}
                    <tr>
                        <td>{{ b.date|date:"d.m.y" }}</td>
                        <td>{{ b.owner.name }}</td>
                        <td>{{ b.owner.office_number }}</td>
                        <td>{{ b.owner.phone }}</td>
                        <td>{{ b.get_duration_display }}</td>
                        <td>
                        <form method="POST" action="{% url 'main:booking_status_update' b.pk %}">
                            {% csrf_token %}
                            <select name="new_status">
                                {% for status in status_choices %}
                                    <option value="{{ status.0 }}"
                                            {% if status.0 == b.status %}selected{% endif %}>{{ status.1 }}</option>
                                {% endfor %}
                            </select>
                            <button type="submit">Изменить</button>
                        </form>
                    </td>
                        <td>{{ b.comment }}</td>
                        
                       
                        <td>
                            <a href="{% url 'main:booking_update' b.pk %}" class="btn btn-warning"
                               style="margin-bottom: 1mm;">Редактировать</a>
                        
                        </td>
                       
                    </tr>

                    {% endfor %}

                    </tbody>
                </table>
            </div>
<div class="row">
                <h3 class="text-left">Активные брони</h3>
               
                <table class="table">
                    <thead>
                    <tr>
                        <th>Дата мероприятия</th>
                        <th>Арендатор </th>
                        <th>Номер офиса </th>
                        <th>Телефон </th>
                        <th>Длительность</th>                        
                        <th>Статус заявки</th>
                        <th>Комментарий</th>
                      
                        
                        
                    </tr>
                    </thead>
                    <tbody>

                    {% for b in approved_booking %}
                    <tr>
                        <td>{{ b.date|date:"d.m.y" }}</td>
                        <td>{{ b.owner.name }}</td>
                        <td>{{ b.owner.office_number }}</td>
                        <td>{{ b.owner.phone }}</td>
                        <td>{{ b.get_duration_display }}</td>
                        <td>
                        <form method="POST" action="{% url 'main:booking_status_update' b.pk %}">
                            {% csrf_token %}
                            <select name="new_status">
                                {% for status in status_choices %}
                                    <option value="{{ status.0 }}"
                                            {% if status.0 == b.status %}selected{% endif %}>{{ status.1 }}</option>
                                {% endfor %}
                            </select>
                            <button type="submit">Изменить</button>
                        </form>
                    </td>
                        <td>{{ b.comment }}</td>
                        
                       
                        <td>
                            <a href="{% url 'main:booking_update' b.pk %}" class="btn btn-warning"
                               style="margin-bottom: 1mm;">Редактировать</a>
                        
                        </td>
                       
                    </tr>

                    {% endfor %}

                    </tbody>
                </table>
            </div>
</div>



{% endblock %}

main/templates/main/car_form.html
{% extends 'main/base.html' %}

{% block content%}

        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            {% if object %}
                            Редактирование информации о доступе
                            {% else %}
                            Сделать запрос на доступ на территорию*
                            {% endif %}
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Отправить запрос</button>
                </div>
            </div>
        </div>

    </form>
        </div>
    *Проверить статус запроса Вы сможете в личном кабинете.
    </div>
</div>
</div>
</div>

</form>
{% endblock %}

main/templates/main/company_detail.html
{% extends 'main/base.html' %}

{% block content%}

    <div class="container">
        <div class="row">
            <!-- Левая часть с изображением -->
            <div class="col-md-0">
                <!-- <img src="/media/{{ product.preview }}/" width="500" height="555"> -->
            </div>

            <!-- Правая часть с информацией о товаре -->
            <div class="col-md-8">
                <h2>{{ labtest.name }}</h2>
                <p>Описание товара: {{ labtest.description }}</p>
                <p>Цена: {{ labtest.price }} руб.</p>
                <p>Время выполнения: {{ labtest.time }} дн.</p>
                <div class="">
                  <form action="{% url 'cart:cart_add' labtest.id %}" method="post">
                      {{ cart_product_form }}
                      {% csrf_token %}
                      <button class="add-to-cart-btn">Положить в корзину</button>
                  </form>

                        {% if user.is_staff %}
                <a href="{% url 'main:labtest_update' labtest.id %}"
                       class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    <a href="{% url 'main:labtest_delete' labtest.id %}"
                       class="btn btn-sm btn-outline-danger">Удалить</a>

                {% endif %}
                    </div>





            </div>
<div class="col-6">

        </div>
    </div>
{% endblock %}

main/templates/main/company_list.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
{% if user.is_manager %}
                <a class="btn btn-outline-primary" href="{% url 'main:company_create' %}">Добавить компанию</a>
{% endif %}
<div class="row mb-2">
    {% for company in company_list %}
        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">

              <h3 class="mb-0">
                <a class="text-dark" href="{% url 'main:company_detail' company.id %}">{{ company }}</a>
              </h3>

                {% if user.is_manager %}

                <a href="{% url 'main:company_update' company.id %}"
                       class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    <a href="{% url 'main:labtest_delete' company.id %}"
                       class="btn btn-sm btn-outline-danger">Удалить</a>

                {% endif %}

            </div>

          </div>
        </div>
    {% endfor %}

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
    {% if user.is_manager %}
    <div class="row mb-2">
        <div class="col-md-4">
          <div class="card flex-md-row mb-4 box-shadow h-md-100" style="background-color: #FF4500;">
            <div class="card-body d-flex flex-column align-items-start">

              <h3 class="mb-0">
                 
                      <a class="text-white" href="{% url 'main:request_list' %}">Посмотреть заявки арендаторов</a>
                 
              </h3>
                          

            </div>

          </div>
        </div>


        <div class="col-md-4">
          <div class="card flex-md-row mb-4 box-shadow h-md-100" style="background-color: #FF4500;">
            <div class="card-body d-flex flex-column align-items-start">

              <h3 class="mb-0">
                  
                <a class="text-white" href="{% url 'main:cars_list' %}">Посмотреть список допущенных авто</a>
                  
              </h3>
             

            </div>

          </div>
        </div>
    <div class="col-md-4">
          <div class="card flex-md-row mb-4 box-shadow h-md-100" style="background-color: #FF4500;">
            <div class="card-body d-flex flex-column align-items-start">

              <h3 class="mb-0">
                  
                <a class="text-white" href="{% url 'main:booking_list' %}">Использование переговорки</a>
                  
              </h3>
             

            </div>

          </div>
        </div>
      </div>
{% endif %}
      <div class="jumbotron p-3 p-md-5 bg-secondary text-light p-2">
        <div class="col-md-12 px-0">
          <h1 class="display-4">Добро пожаловать на наш сайт!</h1>
          <p class="lead my-3">Прошу Вас тестировать функции данного сайта и отправлять все замечания мне на почту olga@noran.ru</p>
            <p class="lead my-3">После регистрации на Вашей странице в профиле Вы сможете отслеживать все Ваши заявки.</p>

        </div>
      </div>

      <div class="row mb-2">
        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">

              <h3 class="mb-0">
                  {% if user.is_authenticated %}
                      <a class="text-dark" href="{% url 'main:request_create' %}">Подать заявку в УК</a>
                  {% else %}
                      <a class="text-dark" href="{% url 'users:login' %}">Подать заявку в УК</a>
                  {% endif %}
              </h3>
              <div class="mb-1 text-muted"></div>
              <p class="card-text mb-auto">Здесь Вы можете напрямую отправить срочную или не очень заявку в службу эксплуатации</p>

            </div>

          </div>
        </div>


        <div class="col-md-6">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">

              <h3 class="mb-0">
                   {% if user.is_authenticated %}
                <a class="text-dark" href="{% url 'main:car_create' %}">Доступ для авто</a>
                   {% else %}
                      <a class="text-dark" href="{% url 'users:login' %}">Доступ для авто</a>
                  {% endif %}
              </h3>
              <div class="mb-1 text-muted"></div>
              <p class="card-text mb-auto">Здесь Вы можете отправить заявку на доступ автотранспорта на территорию двора</p>

            </div>

          </div>
        </div>
      </div>
    </div>



    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8 blog-main">
          

          <div class="blog-post">
            <h2 class="bg-secondary text-light p-2">Новости и объявления</h2>
              
            {% for object in news %}
<div class="col-md-offset-12">
<p class="blog-post-meta">{{ object.date }}</p>
    <p><b><a href="{% url 'news:view' object.slug %}" style="color: black;">{{ object.title }}</a></b></p>
    <p>{{ object.body }}</p>



                          </div>
                                      {% if not loop.last %}
            <hr class="hr-custom">
    {% endif %}
{% endfor %}
             
         <h2 class="bg-secondary text-light p-2">Акции и объявления наших арендаторов</h2>
<a class="text-dark" href="{% url 'announcements:list' %}">В этом разделе арендаторы ДЦ Астор могут оставлять свои объявления и специальные предложения </a></p>
             
{% for object in announcements %}
<div class="col-md-offset-12">
<p class="blog-post-meta">{{ object.created_at }}</p>
<p><a href="{% url 'announcements:view' object.slug %}" style="color: black;">{{ object.title }}</a></p>



                          </div>
                                      {% if not loop.last %}
            <hr class="hr-custom">
    {% endif %}
{% endfor %}




          </div><!-- /.blog-post -->



          <nav class="blog-pagination">

          </nav>

        </div><!-- /.blog-main -->

        <aside class="col-md-4 blog-sidebar">
          <div class="p-3 mb-3 bg-light rounded">
            <h4 class="font-italic">Об Управляющей компании НОРАН</h4>
            <p class="mb-0"> Наша компания была создана в 1998 году и вот уже более 10 лет успешно существует на рынке коммерческого и эксплуатационного управления объектами недвижимости, занимая достойное место среди  действительных  членов  Уральской Палаты Недвижимости </p>

    <p> Сегодня, даже в условиях быстро меняющейся и не простой экономической ситуации, мы работаем для наших клиентов, сохраняя репутацию надежного, ответственного и верного партнера, предоставляющего услуги на уровне международного стандарта качества, способного решить вопросы любой степени сложности строго в соответствии с действующим законодательством Российской Федерации. </p>
          </div>

        


        </aside><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </main><!-- /.container -->

 {% endblock %}